using System;
using System.Collections.Concurrent;
using System.Drawing;
using System.Reflection;

namespace StbGrasshopper
{
    /// <summary>
    /// Loads the 24 x 24 component icons embedded in StbGrasshopper.gha.
    /// The PNG files are generated by tools/icons/build_gh_icons.py, so no
    /// graphics drawing is performed when the plug-in runs.
    /// </summary>
    internal static class StbIcons
    {
        public static Bitmap Analyze => Get("Analyze");
        public static Bitmap AnalyzeFromFile => Get("AnalyzeFromFile");
        public static Bitmap Material => Get("Material");
        public static Bitmap Section => Get("Section");
        public static Bitmap Element => Get("Element");
        public static Bitmap Joint => Get("Joint");
        public static Bitmap GridFrame => Get("GridFrame");
        public static Bitmap Support => Get("Support");
        public static Bitmap PointLoad => Get("PointLoad");
        public static Bitmap LineLoad => Get("LineLoad");
        public static Bitmap AreaLoad => Get("AreaLoad");
        public static Bitmap GravityLoad => Get("GravityLoad");
        public static Bitmap LoadCombination => Get("LoadCombination");
        public static Bitmap AreaTributary => Get("AreaTributary");
        public static Bitmap Assemble => Get("Assemble");
        public static Bitmap AssemblyFromFile => Get("AssemblyFromFile");
        public static Bitmap DatNodes => Get("DatNodes");
        public static Bitmap DatBeams => Get("DatBeams");
        public static Bitmap LoadCases => Get("LoadCases");
        public static Bitmap Displacements => Get("Displacements");
        public static Bitmap Forces => Get("Forces");
        public static Bitmap Reactions => Get("Reactions");
        public static Bitmap DeformedShape => Get("DeformedShape");
        public static Bitmap ForceDiagram => Get("ForceDiagram");
        public static Bitmap Stress => Get("Stress");
        public static Bitmap ViewSupport => Get("ViewSupport");
        public static Bitmap LoadContainer => Get("LoadContainer");
        public static Bitmap MaterialContainer => Get("MaterialContainer");
        public static Bitmap SectionContainer => Get("SectionContainer");
        public static Bitmap ModelContainer => Get("ModelContainer");
        public static Bitmap ElementContainer => Get("ElementContainer");
        public static Bitmap SupportContainer => Get("SupportContainer");

        private const string ResourcePrefix = "StbGrasshopper.Resources.Icons.";

        private static readonly ConcurrentDictionary<string, Bitmap> Cache =
            new ConcurrentDictionary<string, Bitmap>();

        private static Bitmap Get(string name)
        {
            return Cache.GetOrAdd(name, LoadBitmap);
        }

        private static Bitmap LoadBitmap(string name)
        {
            var assembly = typeof(StbIcons).GetTypeInfo().Assembly;
            var resourceName = ResourcePrefix + name + ".png";

            using (var stream = assembly.GetManifestResourceStream(resourceName))
            {
                if (stream == null)
                {
                    throw new InvalidOperationException(
                        "Embedded Grasshopper icon was not found: " + resourceName);
                }

                // Clone the decoded image so the manifest stream can be closed.
                using (var decoded = new Bitmap(stream))
                {
                    return new Bitmap(decoded);
                }
            }
        }
    }
}
